_target_: usaugment.models.classification.BinaryClassificationModel

model:
  _target_: usaugment.models.efficientnet.EfficientNetBN
  model_name: efficientnet-b0
  pretrained: True
  in_channels: ${in_channels}
  num_classes: 1
  dropout_rate: ${dropout}

optimizer_partial:
  _partial_: true
  _target_: torch.optim.Adam
  lr: ${lr}
  weight_decay: ${weight_decay}

label_smoothing: ${label_smoothing}