_target_: usaugment.models.classification.BinaryClassificationModel

model:
  _target_: transformers.SegformerForImageClassification.from_pretrained
  pretrained_model_name_or_path: ${models_dir}/nvidia/mit-b2
  num_labels: 1
  ignore_mismatched_sizes: True

optimizer_partial:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: ${lr}
  weight_decay: ${weight_decay}

label_smoothing: ${label_smoothing}