_target_: usaugment.models.classification.MultiClassClassificationModel

model:
  _target_: transformers.SegformerForImageClassification.from_pretrained
  pretrained_model_name_or_path: ${models_dir}/nvidia/mit-b2
  num_labels: ${num_classes}
  ignore_mismatched_sizes: True

optimizer_partial:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: ${lr}
  weight_decay: ${weight_decay}

num_classes: ${num_classes}
label_smoothing: ${label_smoothing}
