_target_: usaugment.models.segmentation.BinarySegmentationModel

model:
  _target_: transformers.SegformerForSemanticSegmentation.from_pretrained
  pretrained_model_name_or_path: ${models_dir}/nvidia/mit-b2
  num_labels: 1

optimizer_partial:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: ${lr}
  weight_decay: ${weight_decay}
