# @package _global_
defaults:
  - /model: efficientnetb0_multiclass

num_classes: 9
in_channels: 3
label_smoothing: 0.0
lr: 0.000177269
weight_decay: 0.000222434
epochs: 200
dropout: 0.0138161
batch_size: 128
accumulate_grad_batches: 1
task: classification
key_metric: avg_precision
version: butterfly_v4

dataset:
  _target_: usaugment.data.ClassificationDataset
  label_key: label

task_name: ${version}_classification