# @package _global_
defaults:
  - /model: efficientnetb0_multiclass

num_classes: 3
in_channels: 3
label_smoothing: 0.0
lr: 0.000451229
weight_decay: 0.00195327
epochs: 100
dropout: 0.435791
batch_size: 128
accumulate_grad_batches: 1
task: classification
key_metric: avg_precision
version: camus_v4

dataset:
  _target_: usaugment.data.ClassificationDataset
  label_key: label

task_name: ${version}_classification