# @package _global_
defaults:
  - /model: efficientnetb0_binary

in_channels: 3
num_classes: 2
label_smoothing: 0.0
lr: 0.00016865
weight_decay: 0.000482974
epochs: 200
dropout: 0.466939
batch_size: 128
accumulate_grad_batches: 1
task: classification
key_metric: avg_precision
version: covid_blues_v3

dataset:
  _target_: usaugment.data.ClassificationDataset
  label_key: cov_test

task_name: ${version}_classification