# @package _global_
defaults:
  - /model: efficientnetb0_unet_multiclass

num_classes: 3
in_channels: 3
lr: 0.0000382946
weight_decay: 0.000466118
epochs: 200
dropout: 0.0555849
batch_size: 128
accumulate_grad_batches: 1
task: segmentation
key_metric: dice
version: jnuifm_v4

dataset:
  _target_: usaugment.data.SegmentationDataset
  mask_key: spfh_mask

task_name: ${version}_segmentation