# @package _global_
defaults:
  - /model: efficientnetb0_unet_binary

in_channels: 3
lr: 0.000238569
weight_decay: 0.000136489
epochs: 200
dropout: 0.302882
batch_size: 128
accumulate_grad_batches: 1
task: segmentation
key_metric: dice
version: mmotu_v2

dataset:
  _target_: usaugment.data.SegmentationDataset
  mask_key: tumor_mask_binary

task_name: ${version}_segmentation