# @package _global_
defaults:
  - /model: efficientnetb0_unet_multiclass

num_classes: 4
in_channels: 3
lr: 0.000122006
weight_decay: 0.000346011
epochs: 200
dropout: 0.0519524
batch_size: 128
accumulate_grad_batches: 1
task: segmentation
key_metric: dice
version: open_kidney_v3

dataset:
  _target_: usaugment.data.SegmentationDataset
  mask_key: regions_mask

task_name: ${version}_regions_segmentation