# @package _global_
defaults:
  - /model: efficientnetb0_multiclass

in_channels: 3
num_classes: 3
label_smoothing: 0.0
lr: 0.00023479
weight_decay: 0.00421274
epochs: 200
dropout: 0.115265
batch_size: 128
accumulate_grad_batches: 1
task: classification
key_metric: avg_precision
version: pocus_v4

dataset:
  _target_: usaugment.data.ClassificationDataset
  label_key: label

task_name: ${version}_classification