# @package _global_
defaults:
  - /model: efficientnetb0_unet_multiclass

num_classes: 3
in_channels: 3
lr: 0.0002219
weight_decay: 0.00668521
epochs: 200
dropout: 0.234236
batch_size: 128
accumulate_grad_batches: 1
task: segmentation
key_metric: dice
version: psfhs_v2

dataset:
  _target_: usaugment.data.SegmentationDataset
  mask_key: psfh_mask

task_name: ${version}_segmentation