# @package _global_
defaults:
  - /model: efficientnetb0_binary

num_classes: 2
in_channels: 3
label_smoothing: 0.0
lr: 0.000999641
weight_decay: 0.00732425
epochs: 200
dropout: 0.101467
batch_size: 128
accumulate_grad_batches: 1
task: classification
key_metric: avg_precision
version: stanford_thyroid_v4

dataset:
  _target_: usaugment.data.ClassificationDataset
  label_key: label

task_name: ${version}_classification